import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, Building2, ChevronRight, CircleDollarSign, FileQuestion, FileText, Headphones, HelpCircle, MessageSquareText, Phone, Settings, ShieldCheck, UsersRound } from 'lucide-react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { api, jsonBody } from '../../app/api';
import { formatSalaryRange } from '../../app/format';
import type { Job, Person, Session } from '../../app/types';
import { Avatar } from '../../components/Avatar';
import { DetailLine, JobCard, PersonRow } from '../../components/DataCards';
import { StatusTag } from '../../components/StatusTag';
import { Card, EmptyState, Field, FilterSelect, LoadingScreen, Modal, PageHeader, SearchInput } from '../../components/Ui';
import { AppealsPage, MessagesPage } from '../personal/PersonalPages';

interface Catalog { projects: Array<{ id: string; name: string; region: string }>; }

export function SupplierJobs() {
  const [query, setQuery] = useState(''); const [region, setRegion] = useState(''); const [project, setProject] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState('');
  const catalog = useQuery({ queryKey: ['catalog'], queryFn: () => api<Catalog>('/api/catalog') });
  const params = new URLSearchParams(); if (query) params.set('query', query); if (region) params.set('region', region); if (project) params.set('projectId', project); if (type) params.set('jobType', type); if (status) params.set('status', status);
  const jobs = useQuery({ queryKey: ['supplier-jobs', query, region, project, type, status], queryFn: () => api<Job[]>(`/api/jobs?${params}`) });
  return <><SearchInput value={query} onChange={setQuery} placeholder="搜索项目名称或岗位名称" /><div className="filter-row"><FilterSelect label="区域" value={region} onChange={setRegion} options={[{ label: '宜宾市', value: '四川省宜宾市' }, { label: '泸州市', value: '四川省泸州市' }, { label: '成都市', value: '四川省成都市' }]} /><FilterSelect label="项目" value={project} onChange={setProject} options={catalog.data?.projects.map((item) => ({ label: item.name, value: item.id })) ?? []} /><FilterSelect label="岗位类型" value={type} onChange={setType} options={[{ label: '操作工', value: '操作工' }, { label: '质检', value: '质检' }, { label: '技术岗', value: '技术岗' }]} /><FilterSelect label="招聘状态" value={status} onChange={setStatus} options={[{ label: '招聘中', value: 'recruiting' }, { label: '已暂停', value: 'paused' }]} /></div>{jobs.isLoading ? <LoadingScreen /> : jobs.data?.length ? <div className="job-list">{jobs.data.map((job) => <JobCard key={job.id} job={job} portal="supplier" />)}</div> : <EmptyState title="暂无岗位需求" detail="调整筛选条件后重试" />}</>;
}

export function SupplierJobDetail() {
  const { id = '' } = useParams(); const job = useQuery({ queryKey: ['job', id], queryFn: () => api<Job>(`/api/jobs/${id}`) });
  if (job.isLoading) return <LoadingScreen />; if (!job.data) return <EmptyState title="岗位需求不存在" detail="该需求可能已经关闭" />;
  const item = job.data; const gap = Math.max(0, item.headcount - Number(item.appliedCount));
  return <><PageHeader title="岗位详情" back /><div className={`job-hero job-thumb--${item.imageKey}`} style={{ backgroundImage: `linear-gradient(180deg, rgba(7,34,76,.03), rgba(7,34,76,.72)), url(${item.imageUrl})` }}><div><span>{item.projectName}</span><strong>{item.title}</strong></div><StatusTag status={item.status} /></div><Card className="supplier-job-summary"><div className="row row--between"><div><h1>{item.projectName} - {item.title}</h1><p>{item.projectDescription}</p></div></div><div><span>招聘人数<strong>{item.headcount}人</strong></span><span>已报名<strong>{item.appliedCount}人</strong></span><span>剩余缺口<strong>{gap}人</strong></span></div></Card><Card className="detail-section supplier-job-lines"><DetailLine label="岗位职责" value={item.duties} /><DetailLine label="岗位要求" value={item.requirements} /><DetailLine label="薪资福利" value={`${formatSalaryRange(item.salary_min, item.salary_max, false)}，${item.benefits}`} /><DetailLine icon="map" label="工作地点" value={item.address} /><DetailLine icon="time" label="工作时间" value={item.work_time} /><DetailLine label="报名截止" value={item.deadline} /><DetailLine label="项目负责人" value={`${item.managerName} ${item.managerPhone}`} /><DetailLine label="供应商政策" value={item.supplier_policy} /><DetailLine label="政策有效时间" value={`${item.policy_start} 至 ${item.policy_end}`} /><DetailLine label="结费条件" value={item.settlement_condition} /></Card><div className="inline-actions"><a className="secondary-button" href={`tel:${item.managerPhone}`}><Phone size={16} />联系负责人</a><Link className="primary-button" to={`/supplier/people?jobId=${item.id}`}>报名人员</Link></div></>;
}

export function SupplierPeople() {
  const [searchParams] = useSearchParams(); const jobId = searchParams.get('jobId') ?? '';
  const [query, setQuery] = useState(''); const [project, setProject] = useState(''); const [status, setStatus] = useState(''); const [interview, setInterview] = useState(''); const [onboard, setOnboard] = useState('');
  const catalog = useQuery({ queryKey: ['catalog'], queryFn: () => api<Catalog>('/api/catalog') }); const params = new URLSearchParams(); if (query) params.set('query', query); if (project) params.set('projectId', project); if (jobId) params.set('jobId', jobId); if (status) params.set('status', status); if (interview) { const ranges: Record<string, [string, string]> = { today: ['2026-07-22', '2026-07-22'], week: ['2026-07-20', '2026-07-26'], month: ['2026-07-01', '2026-07-31'] }; const range = ranges[interview]!; params.set('interviewFrom', range[0]); params.set('interviewTo', range[1]); } if (onboard) { const ranges: Record<string, [string, string]> = { month: ['2026-07-01', '2026-07-31'], previous: ['2026-06-01', '2026-06-30'] }; const range = ranges[onboard]!; params.set('onboardFrom', range[0]); params.set('onboardTo', range[1]); }
  const people = useQuery({ queryKey: ['supplier-people', query, project, jobId, status, interview, onboard], queryFn: () => api<Person[]>(`/api/people?${params}`) });
  return <><SearchInput value={query} onChange={setQuery} placeholder="搜索姓名或手机号" /><div className="filter-row"><FilterSelect label="项目" value={project} onChange={setProject} options={catalog.data?.projects.map((item) => ({ label: item.name, value: item.id })) ?? []} /><FilterSelect label="当前状态" value={status} onChange={setStatus} options={statusOptions} /><FilterSelect label="面试时间" value={interview} onChange={setInterview} options={[{ label: '今天', value: 'today' }, { label: '本周', value: 'week' }, { label: '本月', value: 'month' }]} /><FilterSelect label="入职时间" value={onboard} onChange={setOnboard} options={[{ label: '本月', value: 'month' }, { label: '上月', value: 'previous' }]} /></div>{people.isLoading ? <LoadingScreen /> : people.data?.length ? <div className="person-list">{people.data.map((person) => <PersonRow key={person.id} person={person} portal="supplier" />)}</div> : <EmptyState title="没有匹配人员" detail="供应商只能查看自己输送的人员" />}</>;
}

const statusOptions = [{ label: '已报名', value: 'registered' }, { label: '已到场', value: 'arrived' }, { label: '面试通过', value: 'interview_passed' }, { label: '待入职', value: 'pending_onboard' }, { label: '已入职', value: 'employed' }, { label: '已离职', value: 'departed' }];

export function SupplierPersonDetail() {
  const { id = '' } = useParams(); const [appealOpen, setAppealOpen] = useState(false); const queryClient = useQueryClient();
  const person = useQuery({ queryKey: ['person', id], queryFn: () => api<Person>(`/api/people/${id}`) });
  const appeal = useMutation({ mutationFn: (data: { description: string; expectedStatus: string; attachmentIds: string[] }) => api('/api/appeals', { method: 'POST', ...jsonBody({ type: 'person_status', subjectId: id, ...data }) }), onSuccess: async () => { setAppealOpen(false); await queryClient.invalidateQueries({ queryKey: ['appeals'] }); } });
  if (person.isLoading) return <LoadingScreen />; if (!person.data) return <EmptyState title="人员不存在" detail="该人员不属于当前供应商" />; const item = person.data;
  return <><PageHeader title="人员详情" back /><Card className="supplier-person-head"><Avatar name={item.name} size={58} /><div><div><h1>{item.name}</h1><StatusTag status={item.status} /></div><p>{item.phone}</p><span>{item.projectName} · {item.jobTitle}</span></div></Card><Card className="supplier-person-info"><DetailLine label="身份证号" value={item.idCard} /><DetailLine label="员工编号" value={item.employeeNo ?? '未生成'} /><DetailLine label="报名时间" value={item.appliedAt.slice(0,10)} /><DetailLine label="面试时间" value={item.interviewAt ? new Date(item.interviewAt).toLocaleString('zh-CN') : '—'} /><DetailLine label="入职时间" value={item.onboardDate ?? '—'} /><DetailLine label="当前在职天数" value={`${item.employmentDays ?? 0}天`} /><DetailLine label="离职时间" value={item.departureDate ?? '—'} /><DetailLine label="适用政策" value="A类政策：入职满30天奖励500元" /></Card><Card className="supplier-timeline"><h2>状态流程</h2><div className="horizontal-life">{['报名','面试','入职','在职','离职'].map((label, index) => <span className={index <= lifeIndex(item.status) ? 'done' : ''} key={label}><i>{index + 1}</i><b>{label}</b></span>)}</div></Card><button className="secondary-button full-button" type="button" onClick={() => setAppealOpen(true)}><FileQuestion size={16} />状态不正确？提交申诉</button><StatusAppealModal open={appealOpen} onClose={() => setAppealOpen(false)} onSubmit={(data) => appeal.mutate(data)} pending={appeal.isPending} error={appeal.error?.message} /></>;
}

function lifeIndex(status: string) { return ({ registered: 0, arrived: 1, interview_passed: 1, interview_failed: 1, pending_onboard: 2, employed: 3, departed: 4, withdrawn: 1 } as Record<string,number>)[status] ?? 0; }

function StatusAppealModal({ open, onClose, onSubmit, pending, error }: { open: boolean; onClose: () => void; onSubmit: (data: { description: string; expectedStatus: string; attachmentIds: string[] }) => void; pending: boolean; error?: string | undefined }) {
  const [expectedStatus, setExpectedStatus] = useState('employed'); const [description, setDescription] = useState('');
  const [attachments, setAttachments] = useState<Array<{ id: string; originalName: string }>>([]);
  const upload = useMutation({ mutationFn: async (file: File) => { const body = new FormData(); body.append('file', file); return api<{ id: string; originalName: string }>('/api/attachments', { method: 'POST', body }); } });
  const addFiles = async (files: FileList | null) => { for (const file of Array.from(files ?? []).slice(0, 5 - attachments.length)) { const saved = await upload.mutateAsync(file); setAttachments((current) => [...current, saved]); } };
  return <Modal open={open} title="人员状态申诉" onClose={onClose} footer={<button type="button" className="primary-button" disabled={pending || upload.isPending || description.length < 5} onClick={() => onSubmit({ expectedStatus, description, attachmentIds: attachments.map((item) => item.id) })}>{pending ? '提交中…' : upload.isPending ? '上传中…' : '提交申诉'}</button>}><div className="form-grid"><Field label="正确状态" required><select value={expectedStatus} onChange={(event) => setExpectedStatus(event.target.value)}>{statusOptions.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select></Field><Field label="申诉原因" required><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="请说明正确状态与判断依据" /></Field><label className="upload-placeholder"><FileText /><span>{upload.isPending ? '正在上传…' : '添加凭证（可选）'}</span><small>支持图片或 PDF，最多5个文件</small><input type="file" hidden multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(event) => void addFiles(event.target.files)} /></label>{attachments.length > 0 && <ul className="attachment-list">{attachments.map((item) => <li key={item.id}><FileText size={14} />{item.originalName}<button type="button" onClick={() => setAttachments((current) => current.filter((file) => file.id !== item.id))}>移除</button></li>)}</ul>}{(error || upload.error) && <p className="form-error">{error ?? upload.error?.message}</p>}</div></Modal>;
}

interface SettlementData { id?: string; month: string; status?: string; overview: { dueAmount: number; confirmedAmount: number; pendingAmount: number; disputedAmount: number }; items: Array<{ id: string; name: string; phone: string; projectName: string; jobTitle: string; onboardDate: string; employmentDays: number; policy: string; dueAmount: number; actualAmount: number; status: string }>; }

export function SupplierSettlements() {
  const [month, setMonth] = useState('2026-07'); const [selected, setSelected] = useState<SettlementData['items'][number] | null>(null); const queryClient = useQueryClient();
  const settlement = useQuery({ queryKey: ['settlement', month], queryFn: () => api<SettlementData>(`/api/settlements?month=${month}`) });
  const confirm = useMutation({ mutationFn: () => api(`/api/settlements/${settlement.data?.id}/confirm`, { method: 'POST' }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['settlement'] }) });
  if (settlement.isLoading) return <LoadingScreen />; const data = settlement.data;
  return <><label className="month-picker"><span>结算月份</span><select value={month} onChange={(event) => setMonth(event.target.value)}><option value="2026-07">2026年07月</option><option value="2026-06">2026年06月</option></select></label><section className="settlement-overview"><MoneyMetric label="本月应结金额" value={data?.overview.dueAmount ?? 0} tone="blue" /><MoneyMetric label="已确认金额" value={data?.overview.confirmedAmount ?? 0} tone="green" /><MoneyMetric label="待确认金额" value={data?.overview.pendingAmount ?? 0} tone="orange" /><MoneyMetric label="有争议金额" value={data?.overview.disputedAmount ?? 0} tone="red" /></section><div className="row row--between"><h2 className="section-title">结算明细</h2>{data?.id && <button className="text-button" type="button" disabled={confirm.isPending} onClick={() => confirm.mutate()}>确认无争议明细</button>}</div><div className="settlement-list">{data?.items.map((item) => <button className="settlement-row" type="button" key={item.id} onClick={() => setSelected(item)}><div className="row row--between"><div className="row"><Avatar name={item.name} size={38} /><div><strong>{item.name}</strong><p>{item.projectName}-{item.jobTitle}</p></div></div><StatusTag status={item.status} /></div><dl><div><dt>入职时间</dt><dd>{item.onboardDate ?? '—'}</dd></div><div><dt>在职天数</dt><dd>{item.employmentDays}天</dd></div><div><dt>应结金额</dt><dd>¥{item.dueAmount.toLocaleString()}</dd></div><div><dt>实结金额</dt><dd>¥{item.actualAmount.toLocaleString()}</dd></div></dl></button>)}</div>{!data?.items.length && <EmptyState title="暂无结算明细" detail="选择其他月份查看历史结算" />}<SettlementDetailModal item={selected} onClose={() => setSelected(null)} /></>;
}

function MoneyMetric({ label, value, tone }: { label: string; value: number; tone: string }) { return <Card className={`money-metric money-metric--${tone}`}><span><CircleDollarSign /></span><div><small>{label}</small><strong>¥ {value.toLocaleString(undefined, { minimumFractionDigits: 2 })}</strong></div></Card>; }

function SettlementDetailModal({ item, onClose }: { item: SettlementData['items'][number] | null; onClose: () => void }) { return <Modal open={Boolean(item)} title="结算明细" onClose={onClose}>{item && <><div className="row row--between"><div><strong>{item.name}</strong><p className="muted small">{item.phone} · {item.projectName} · {item.jobTitle}</p></div><StatusTag status={item.status} /></div><div className="settlement-detail-lines"><DetailLine label="入职时间" value={item.onboardDate ?? '—'} /><DetailLine label="当前在职天数" value={`${item.employmentDays}天`} /><DetailLine label="适用政策" value={item.policy} /><DetailLine label="应结金额" value={`¥${item.dueAmount}`} /><DetailLine label="实结金额" value={`¥${item.actualAmount}`} /></div><Link className="secondary-button full-button" to="/supplier/appeals">对本明细有疑问？提交申诉</Link></>}</Modal>; }

interface SupplierProfileData { id: string; name: string; contact: string; phone: string; grade: string; projectCount: number; monthlyPeople: number; }

export function SupplierMe({ session }: { session: Session }) {
  const profile = useQuery({ queryKey: ['supplier-profile'], queryFn: () => api<SupplierProfileData>('/api/supplier/profile') }); const item = profile.data;
  return <><section className="supplier-profile-hero"><div className="supplier-brand"><span><Building2 /></span><div><h1>{item?.name ?? '供应商企业'}</h1><p>联系人　{item?.contact ?? session.name}</p><p>联系电话　{item?.phone ?? '正在读取企业档案…'}</p></div><StatusTag status="confirmed" label={item?.grade ?? '合作供应商'} /></div></section><section className="supplier-stats"><Card><span>合作项目</span><strong>{item?.projectCount ?? 0}<small>个</small></strong></Card><Card><span>本月输送人数</span><strong>{item?.monthlyPeople ?? 0}<small>人</small></strong></Card></section><Card className="menu-list supplier-menu"><div className="supplier-level"><ShieldCheck />当前合作等级<span>{item?.grade ?? '—'}</span></div><Link to="/supplier/appeals"><MessageSquareText />我的申诉<i>2</i><ChevronRight /></Link><Link to="/supplier/messages"><Bell />消息通知<i>4</i><ChevronRight /></Link><a href="tel:08318881234"><Phone />联系公司<span>0831-8881234</span><ChevronRight /></a><Link to="/supplier/help"><HelpCircle />帮助与设置<ChevronRight /></Link></Card></>;
}

export function SupplierAppeals() { return <AppealsPage supplier />; }
export { MessagesPage as SupplierMessages };
